name: Node CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_for_PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2s
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - run: npm run build
